### ISSUE TITLE
Citing lowrankapprox Julia package

### ISSUE THREAD

**Issue by pcarbo** [JuliaMatrices/LowRankApprox.jl#8]
I would like to cite the `lowrankapprox` Julia package in a manuscript we will be submitting soon for review. Can you please provide a suggested citation with a title and list of authors? Thank you.

**Comment by klho** [comment]
Thanks for your interest. Please cite as:

Kenneth L. Ho & Sheehan Olver (2018) LowRankApprox.jl: Fast low-rank matrix approximation in Julia. Zenodo. http://doi.org/10.5281/zenodo.1254147

following the Zenodo record https://zenodo.org/record/1254147.

I was the original author on this package and @dlfivefifty has since done a lot of work in keeping it up to date and now also adding new features.

**Comment by pcarbo** [comment]
@klho Great, thank you!
